// server/utils/textMatcher.js

/**
 * Normalizes text for comparison by lowercasing and removing punctuation.
 */
function normalizeText(text) {
  if (!text) return "";
  // Remove punctuation but keep alphanumeric and spaces
  return text.toLowerCase().replace(/[^\w\s]/g, '').trim();
}

/**
 * A list of common stop words that shouldn't be highlighted on their own.
 */
const STOP_WORDS = new Set([
  'a', 'an', 'and', 'are', 'as', 'at', 'be', 'but', 'by', 'for',
  'if', 'in', 'into', 'is', 'it', 'no', 'not', 'of', 'on', 'or',
  'such', 'that', 'the', 'their', 'then', 'there', 'these',
  'they', 'this', 'to', 'was', 'will', 'with', 'which', 'who', 'what'
]);

/**
 * Checks if a phrase consists entirely of stop words.
 */
function isOnlyStopWords(words) {
  return words.every(word => STOP_WORDS.has(word.toLowerCase()));
}

/**
 * Highlights sequences of words in the AI response that exist verbatim in the source context.
 * 
 * @param {string} aiText - The complete text generated by the AI
 * @param {string} contextText - The complete chunk of text from the source documents
 * @param {number} minMatchWords - The minimum number of consecutive words required to trigger a highlight
 * @returns {string} The aiText with HTML <u> tags wrapped around matching phrases
 */
function highlightSourceMatches(aiText, contextText, minMatchWords = 5) {
  if (!aiText || !contextText) return aiText || "";

  // 1. Process Context into a Fast Lookup Set of N-Grams
  const contextWords = normalizeText(contextText).split(/\s+/);
  if (contextWords.length < minMatchWords) return aiText;
  
  const contextNgrams = new Set();
  for (let i = 0; i <= contextWords.length - minMatchWords; i++) {
    const ngram = contextWords.slice(i, i + minMatchWords).join(' ');
    contextNgrams.add(ngram);
  }

  // 2. Tokenize the AI Text while Preserving Original Formatting
  // We use a regex to split by word boundaries so we can keep punctuation/spaces
  const tokens = aiText.split(/(\b\w+\b)/).filter(t => t !== '');
  
  // Create arrays for logic processing
  const normalizedWords = []; // just the words, normalized
  const originalTokens = [];  // original text (words + punctuation/spacing)
  const tokenToWordMap = [];  // maps original word tokens to the normalized word index

  let wordIndex = 0;
  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    originalTokens.push(token);
    
    // If it's a word character sequence
    if (/\b\w+\b/.test(token)) {
      normalizedWords.push(token.toLowerCase());
      tokenToWordMap[i] = wordIndex;
      wordIndex++;
    } else {
      tokenToWordMap[i] = -1; // Not a word
    }
  }

  if (normalizedWords.length < minMatchWords) return aiText;

  // 3. Sliding Window to Find Matches in the AI Text
  const highlightWordIndices = new Set();

  for (let i = 0; i <= normalizedWords.length - minMatchWords; i++) {
    const aiNgramWords = normalizedWords.slice(i, i + minMatchWords);
    
    // Filter out purely stop-word N-Grams
    if (isOnlyStopWords(aiNgramWords)) continue;

    const aiNgramStr = aiNgramWords.join(' ');

    if (contextNgrams.has(aiNgramStr)) {
      // It's a match! Mark these word indices for highlighting
      for (let j = 0; j < minMatchWords; j++) {
        highlightWordIndices.add(i + j);
      }
    }
  }

  if (highlightWordIndices.size === 0) return aiText;

  // 4. Reconstruct String with HTML Tags
  let result = "";
  let insideU = false;

  for (let i = 0; i < originalTokens.length; i++) {
    const token = originalTokens[i];
    const wIndex = tokenToWordMap[i];

    if (wIndex !== -1 && highlightWordIndices.has(wIndex)) {
      // This word should be highlighted
      if (!insideU) {
        result += "<u>";
        insideU = true;
      }
      result += token;
    } else {
      // This is either punctuation, space, or an unhighlighted word
      
      // If we are exiting a highlight block, close the tag BEFORE adding the non-highlighted token
      if (insideU) {
        // Edge case: if the token is just a trailing space or punctuation right after a highlighted word,
        // it often looks cleaner to include punctuation inside the underline, but for strictness 
        // we'll close the tag as soon as we hit a non-matching word or structural space.
        
        // Let's keep spaces inside the tag if the next word is ALSO highlighted
        // Look ahead to the next actual word
        let nextWordIsHighlighted = false;
        for (let next = i; next < originalTokens.length; next++) {
            const nextWIndex = tokenToWordMap[next];
            if(nextWIndex !== -1) {
                nextWordIsHighlighted = highlightWordIndices.has(nextWIndex);
                break;
            }
        }

        if(!nextWordIsHighlighted && /\w/.test(token)) {
             result += "</u>";
             insideU = false;
        } else if (!nextWordIsHighlighted && !/\w/.test(token)) {
             // It's a space or punctuation after a highlighted block. Close it tight.
             result += "</u>";
             insideU = false;
        }

      }
      result += token;
    }
  }

  if (insideU) {
    result += "</u>";
  }

  // Clean up any empty or malformed tags caused by pure symbol isolation
  return result.replace(/<u>\s*<\/u>/g, '');
}

module.exports = {
  highlightSourceMatches,
  normalizeText
};
